# Generated by Django 4.0.4 on 2023-05-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non-binary', 'Non-binary'), ('genderqueer', 'Genderqueer'), ('agender', 'Agender')], max_length=20, verbose_name='Your gender'),
        ),
    ]
