# Generated by Django 4.0.4 on 2022-05-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_emailverirecord_remove_user_age_remove_user_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVeriRecord',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='', verbose_name='фотография'),
        ),
    ]
