# Generated by Django 4.0.4 on 2022-06-03 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_user_ph'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user_first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_first', to=settings.AUTH_USER_MODEL)),
                ('user_second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_second', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
