# Generated by Django 4.0.4 on 2022-06-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_chatname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatname',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
