# Generated by Django 4.0.4 on 2023-01-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hash',
            field=models.CharField(default=None, max_length=64, unique=True),
        ),
    ]
