# Generated by Django 4.0.4 on 2022-05-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_emailverirecord_remove_user_age_user_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.svg', upload_to='<django.db.models.fields.EmailField>', verbose_name='фотография'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(null=True, verbose_name='дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='имя'),
        ),
    ]
