# Generated by Django 4.0.4 on 2022-05-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_avatar_alter_user_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('парень', 'парень'), ('девушка', 'девушка')], max_length=20, null=True),
        ),
    ]
