# Generated by Django 4.0.4 on 2022-05-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True, verbose_name='дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('парень', 'парень'), ('девушка', 'девушка')], max_length=20, null=True, verbose_name='Ваш пол'),
        ),
    ]
