# Generated by Django 4.0.4 on 2022-05-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_user_birthday_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.IntegerField(null=True, verbose_name='дата рождения'),
        ),
    ]
