# Generated by Django 4.0.4 on 2022-07-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_chatname_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='users', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.IntegerField(null=True, verbose_name='Your age'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20, null=True, verbose_name='Your gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=20, verbose_name='Name'),
        ),
    ]
